{% set name = "cfgv" %}
{% set version = "3.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e52591d4c5f5dead8e0f673fb16db7949d2cfb3f7da4582893288f0ded8fe560

build:
  number: 0
  script: pip install . --no-deps --ignore-installed
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6.1
  run:
    - python >=3.6.1

test:
  imports:
    - cfgv

about:
  home: https://github.com/asottile/cfgv
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Validate configuration and produce human readable error messages.
  description: Validate configuration and produce human readable error messages.

extra:
  recipe-maintainers:
    - nicoddemus
